In [1]:
import numpy as np

# Basic array creation 

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a[0])

[1 2 3 4]


In [4]:
a[1]

array([5, 6, 7, 8])

In [5]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [10]:
np.empty(2)

array([1., 1.])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

In [12]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [14]:
np.linspace(0,10,num =5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
np.ones(2,dtype = int)

array([1, 1])

# Adding,removing and sorting elements

In [17]:
arr = np.array([2,1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [20]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [22]:
np.concatenate((x,y),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [25]:
np.concatenate((x,y),axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [26]:
a = np.arange(6)

In [27]:
a

array([0, 1, 2, 3, 4, 5])

In [28]:
b = a.reshape(3,2)

In [29]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

# convert a 1D array into a 2D array

In [30]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [31]:
a2 = a[np.newaxis,:]
a2.shape

(1, 6)

In [32]:
row_vector = a[np.newaxis,:]
row_vector.shape

(1, 6)

In [33]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [34]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [37]:
b = np.expand_dims(a,axis= 0)
b.shape

(1, 6)

In [38]:
c = np.expand_dims(a,axis=1)
c.shape

(6, 1)

# Indexing and slicing

In [39]:
data = np.array([1,2,3])

In [40]:
data[1]

np.int64(2)

In [41]:
data[0:2]

array([1, 2])

In [42]:
data[1:]

array([2, 3])

In [43]:
data[-2:]

array([2, 3])

In [44]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [45]:
print(a[a<5])

[1 2 3 4]


In [46]:
five_up = a[a >=5]
print(five_up)

[ 5  6  7  8  9 10 11 12]


In [47]:
print(a[a%2 == 0])

[ 2  4  6  8 10 12]


In [48]:
print(a[a%5==0])

[ 5 10]


In [50]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
c = a[(a>2)&(a<11)]

In [52]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
d = a[(a>5) | (a==5)]

In [57]:
print(d)

[ 5  6  7  8  9 10 11 12]


In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# create an array from existing data

In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [65]:
arr1 = a[3:8]

In [66]:
arr1

array([4, 5, 6, 7, 8])

In [70]:
a1 = np.array([[1,1],[2,2]])
a2 = np.array([[3,3],[4,4]])

In [71]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [72]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [73]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [75]:
b1 = a[0]
b1

array([1, 2, 3, 4])

In [77]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [78]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [79]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b2 = a.copy()

In [84]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

In [86]:
data = np.array([1,2])
ones = np.ones(2,dtype=int)
data + ones

array([2, 3])

In [87]:
data - ones

array([0, 1])

In [88]:
data * data

array([1, 4])

In [89]:
data / data

array([1., 1.])

In [90]:
a = np.array([1,2,3,4])
a.sum()

np.int64(10)

In [92]:
b = np.array([[1,1],[2,2]])
b.sum(axis=0)

array([3, 3])

In [93]:
b.sum(axis = 1)

array([2, 4])

In [94]:
a

array([1, 2, 3, 4])

In [95]:
a.min()

np.int64(1)

In [96]:
a.max()

np.int64(4)

In [97]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [98]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
data[0,1]

np.int64(2)

In [100]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [101]:
data[0:2,0]

array([1, 3])

In [102]:
data[0,0:2]

array([1, 2])

In [103]:
data.min()

np.int64(1)

In [104]:
data.max()

np.int64(6)

In [105]:
data.sum()

np.int64(21)

# unique items and counts

In [106]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [107]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [109]:
unique_values,indices_list = np.unique(a,return_index = True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [112]:
unique_values,occurrance_list = np.unique(a,return_counts=True)
print(occurrance_list)

[3 2 2 2 1 1 1 1 1 1]


In [113]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [114]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [115]:
unique_rows = np.unique(a_2d,axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [116]:
unique_colms = np.unique(a_2d,axis=1)

In [117]:
print(unique_colms)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [118]:
unique_rows,indices,occurrences=np.unique(a_2d,axis=0,return_index=True,return_counts=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [119]:
print(indices)

[0 1 2]


In [120]:
print(occurrences)

[2 1 1]


# reverse an array

In [121]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
reversed_array = np.flip(arr)
print(reversed_array)

[8 7 6 5 4 3 2 1]


In [123]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
reversed_arr_rows = np.flip(arr_2d,axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [125]:
reversed_arr_colms = np.flip(arr_2d,axis=1)
print(reversed_arr_colms)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [126]:
arr_2d[1]=np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [128]:
arr_2d[:,0]=np.flip(arr_2d[:,0])
print(arr_2d)

[[ 9 10  3  4]
 [ 8  7  6  5]
 [ 1  2 11 12]]
