In [1]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [2]:
type(my_list)

list

In [3]:
import numpy as np
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.zeros(1)

array([0.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [13]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.random.rand(5)

array([0.58287882, 0.18488331, 0.72643789, 0.51847796, 0.94944655])

In [15]:
np.random.rand(3,3)

array([[0.48507207, 0.37605097, 0.34179262],
       [0.38333139, 0.9161293 , 0.48357968],
       [0.28159679, 0.70576168, 0.08017949]])

In [19]:
print(np.random.randint((3,3),dtype=int))

[1 2]


In [21]:
print(np.random.randint(3,size=3,dtype=int))

[1 2 1]


In [22]:
print(np.random.randint(5,size = (3,3),dtype=int))

[[1 4 4]
 [2 1 1]
 [3 3 0]]


In [25]:
np.random.randint(0,10,5)

array([4, 5, 2, 5, 6], dtype=int32)

In [27]:
ri=np.arange(0,100)
ri

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
ri = np.arange(0,100).reshape(10,10)
ri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
ri.shape

(10, 10)

In [32]:
len(ri)

10

In [33]:
id(ri)

2266190564112

In [34]:
ri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
ri[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
ri[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
ri[:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
ri[:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [39]:
ri[2:7]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [41]:
ri[-5:-3]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [42]:
ri[::1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
ri[::2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [44]:
ri[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [45]:
ri[0:6:2]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
ri[-6:-1:3]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [49]:
ri

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [50]:
ri[1:5,2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

In [51]:
ri[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [52]:
ri[7:10,7:10]

array([[77, 78, 79],
       [87, 88, 89],
       [97, 98, 99]])

In [54]:
ri[1,3]

np.int64(13)

In [55]:
ri[6,6]

np.int64(66)

In [56]:
print(ri[5,5])

55


In [57]:
ri > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [58]:
ri<=30

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [59]:
ri[ri<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
ri[ri<=30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
ri[ri==50]

array([50])

In [63]:
ri[ri>90]

array([91, 92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
ri[ri!=90]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Array functions

# array creation functions

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
print("array a:\n",a)

array a:
 [1 2 3 4]


In [7]:
a =np.arange(3)
print(a)

[0 1 2]


In [9]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [16]:
a = np.zeros(3,dtype=int)
a

array([0, 0, 0])

In [23]:
a = np.zeros((5,3),dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [26]:
a = np.ones((4,4),dtype=complex)
print(a)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


In [27]:
a = np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [31]:
a = np.identity(4,dtype=int)
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# array manupulation functions

In [32]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [39]:
reshaped = np.arange(0,10).reshape(2,5)
print("reshaped array is:\n",reshaped)

reshaped array is:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
a1 = np.array([[1,2],[3,4],[5,6],[7,8]])
flattened = np.ravel(a1)
print("flattened array is:\n",flattened)

flattened array is:
 [1 2 3 4 5 6 7 8]


In [41]:
a2 = np.array([[1,5],[4,8]])
transposed = np.transpose(a2)
print("transposed array is :\n",transposed)

transposed array is :
 [[1 4]
 [5 8]]


In [43]:
a3 = np.array([1,3])
a4 = np.array([2,4])
stacked = np.vstack([a3,a4])
print("vertically stacked array :\n",stacked)

vertically stacked array :
 [[1 3]
 [2 4]]


In [44]:
a3 = np.array([1,3])
a4 = np.array([2,4])
stacked = np.hstack([a3,a4])
print("horizontal stacked array :\n",stacked)

horizontal stacked array :
 [1 3 2 4]


# mathematical functions

In [45]:
a = np.array([1,2,3,4])
added = np.add(a,2)
print(added)

[3 4 5 6]


In [48]:
power = np.power(a,2)
print(power)

[ 1  4  9 16]


In [49]:
sqrt = np.sqrt(a)
print(sqrt)

[1.         1.41421356 1.73205081 2.        ]


In [50]:
a 

array([1, 2, 3, 4])

In [52]:
b = np.array([1,2,4,5])
b

array([1, 2, 4, 5])

In [53]:
dot_product = np.dot(a,b)
print(dot_product)

37


# statistical functions

In [54]:
a

array([1, 2, 3, 4])

In [57]:
mean = np.mean(a)
print("mean is",mean)

mean is 2.5


In [59]:
std_dev = np.std(a)
print(std_dev)

1.118033988749895


In [60]:
var = np.var(a)
print(var)

1.25


In [61]:
minimum = np.min(a)
print(minimum)

1


In [62]:
maximum = np.max(a)
print(maximum)

4


# random sampling functions

In [63]:
a = np.random.rand(4)

In [64]:
a

array([0.81277156, 0.34298473, 0.68112939, 0.25805804])

In [71]:
a = np.random.randint(1,5,4)

In [72]:
print(a)

[4 4 2 3]


In [76]:
np.random.seed(0)
np.random.randint(1,5,4)

array([1, 4, 2, 1], dtype=int32)

In [80]:
x  = np.random.randint(0,10,5)
print(x)

[8 1 6 7 7]


# boolian & logical 

In [83]:
y = np.array([True,True,False])
forall = np.all(y)
print(forall)

False


In [86]:
y = np.array([True,True,False])
forany = np.any(y)
print(forany)

True


In [87]:
y = np.array([False,False,False])
forall = np.all(y)
print(forall)

False


In [88]:
y = np.array([False,False,False])
forany = np.any(y)
print(forany)

False
